# Generated by Django 4.0.3 on 2022-03-14 13:00

from django.db import migrations, models
import django.db.models.deletion
from tareas.models import tipo_masivo


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def insert_init_tipo_masivo(apps, schema_editor):
        tipo_masivo_qs = tipo_masivo.objects.filter(tarea="clientes_bulk")
        message: str = "No fue posible crear el tipo_masivo clientes_bulk"
        if not tipo_masivo_qs.exists() and tipo_masivo_qs.count() != 1:
            tipo_masivo.objects.create(
                nombre="Cargue de Clientes",
                activo="S",
                tiene_adjunto="N",
                tarea="clientes_bulk",
                estructura="client_name;category_id;city_id",
            )

            message: str = "tipo_masivo clientes_bulk creado correctamente"
        print(message)

    def undo_init_tipo_masivo(apps, schema_editor):
        tipo_masivo.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name="masivos_file_adjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("registro", models.IntegerField()),
                ("usuario_id", models.CharField(blank=True, max_length=32)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(blank=True, max_length=30, null=True)),
                ("observaciones", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="reports/adjuntos/%Y/%m/"),
                ),
                ("masivo_id", models.IntegerField(blank=True)),
                ("radicado_id", models.IntegerField(blank=True)),
            ],
            options={
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="masivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tarea", models.CharField(blank=True, max_length=150, null=True)),
                ("registro", models.IntegerField()),
                ("resultado", models.CharField(blank=True, max_length=4000, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("usuario_id", models.CharField(blank=True, max_length=32)),
                ("identificador", models.CharField(blank=True, max_length=25)),
                ("tipo_identificador", models.CharField(blank=True, max_length=25)),
                ("masivo_file_id", models.IntegerField()),
            ],
            options={
                "ordering": ["-id", "tarea"],
            },
        ),
        migrations.CreateModel(
            name="tipo_masivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("activo", models.CharField(max_length=1)),
                ("tiene_adjunto", models.CharField(max_length=1)),
                ("tarea", models.CharField(blank=True, max_length=120, null=True)),
                ("estructura", models.CharField(max_length=2000)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="masivos_file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("usuario_id", models.CharField(blank=True, max_length=32)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(blank=True, max_length=20, null=True)),
                ("observaciones", models.CharField(blank=True, max_length=2000, null=True)),
                ("archivo", models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/")),
                ("masivo_id", models.IntegerField(blank=True, null=True)),
                (
                    "tipo_masivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="tareas.tipo_masivo"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RunPython(insert_init_tipo_masivo, reverse_code=undo_init_tipo_masivo),
    ]
